# Change these first
owner: flky-dev # Your GitHub organization or username, where this repository lives
repo: status.flky.dev # The name of this repository

sites:
  - name: Blog
    url: https://blog.flky.dev
  - name: Social Media
    url: https://social.flky.dev
  - name: Link Shortener
    url: https://s.flky.dev
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Analytics
    url: https://analytics.flky.dev
  - name: Content Delivery Network
    url: https://cdn.flky.dev

assignees:
  - flonky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.flky.dev
  logoUrl: https://cdn.flky.dev/general/pfp.webp
  favicon: https://cdn.flky.dev/general/favicon1.ico
  name: flky.dev
  introTitle: "Uptime Monitoring"
  introMessage: This status page monitors pages on the flky.dev domain.
  customHeadHtml: "<script async src="https://analytics.flky.dev/tracker.js" data-ackee-server="https://analytics.flky.dev" data-ackee-domain-id="c31ad4c3-047f-4bb1-b426-9018aee46456"></script>"
  theme: dark
